Add support for netstandard2.0
Cimpress-MCP/serilog-sinks-awscloudwatch pull request #137
Opened 2024-05-10 15:03 UTC by a-jackson

Requires reverting the code to C# 7.3 and making the DisposeAsync conditional on the net6.0 build

2024-05-10 16:38 UTC, wparad commented
I'm sorry this is too many changes, we can't support the validation that would be required here. As I mentioned in the issue, only if the changes were minimal would we be able to effectively support it. But like this, I'm afraid the burden is too high. In this case, I might suggest forking the repo to make those changes.

2024-05-11 09:28 UTC, wparad requested changes
After further review, we've agreed internally that we can potentially accept this change with some minor suggested changes. Thank you for providing this!

2024-05-11 09:28 UTC, wparad commented on src/Serilog.Sinks.AwsCloudWatch/Serilog.Sinks.AwsCloudWatch.csproj
> +  <PropertyGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
This is brittle, can we remove this check and directly inline a complier flag based on the availability of the feature. Or alternatively only if that's not possible, invert this condition so that the feature is included by default.

2024-05-20 08:14 UTC, a-jackson commented on src/Serilog.Sinks.AwsCloudWatch/Serilog.Sinks.AwsCloudWatch.csproj
> +  <PropertyGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
Thanks, I have inverted the the condition. I wasn't expecting this to need so many changes but having to downgrade to C# 7.3 forced it.

2024-05-20 08:38 UTC, wparad commented on src/Serilog.Sinks.AwsCloudWatch/CloudWatchLogSink.cs
> +#if FEATURE_ASYNCDISPOSABLE
According to this https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives we should be able to use something like 
```suggestion
#if NET8_0_OR_GREATER
```
And then we don't need the custom property, because this property is already defined by the framework.

2024-05-20 08:40 UTC, wparad commented on src/Serilog.Sinks.AwsCloudWatch/Serilog.Sinks.AwsCloudWatch.csproj
> +  <PropertyGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
So after some digging I found, https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives, so maybe we can throw that in, instead.

2024-05-20 08:51 UTC, a-jackson commented on src/Serilog.Sinks.AwsCloudWatch/CloudWatchLogSink.cs
> +#if FEATURE_ASYNCDISPOSABLE
I've done that now, with NET6_0_OR_GREATER as that's the other target framework. I forgot that was an option as my company's coding style is to make specific feature flags as I did but I agree, this is better.

2024-05-20 09:07 UTC, wparad approved these changes

2024-05-20 09:08 UTC, merged